[workspace]
resolver = "2"
members = [
    "crates/fw-helper-core",
    "crates/fw-helper-client",
    "crates/fw-helperctl",
    "crates/fw-helperd",
    "crates/fw-helper-gui",
    "crates/fw-helper-restore-fan",
]

[workspace.package]
version = "0.0.5"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/Wooloomooloo2/fw-helper"
rust-version = "1.85"
